# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GD-Barcode-Image
version:      1.02
version_from: lib/GD/Barcode/Image.pm
installdirs:  site
requires:
    GD:                            0
    GD::Barcode:                   0
    Image::Magick:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
